modules:
  data: "AmexDataManager"
  model: "AmexCAT"

dataset:
  prepare: true
  sampling: "NA"

model:
  train:
    itr: 1
    load_from: ""
    train: true
    save: true

  clf:
    init:
      train_dir: "output/Amex"
      objective: "binary:logistic"
      tree_method: hist
      booster: "dart"
      use_label_encoder: false
      learning_rate: 0.002
      n_jobs: 8

    search:
      cv: 5

      n_estimators:
        low: 5
        high: 1500
        q: 1

      max_depth:
        low: 2
        high: 80
        q: 1
