modules:
  data: "AmexDataManager"
  model: "LGB_Hyperopt"
  metric: "Amex"

dataset:
  prepare: false
  sampling: "NA"

model:
  train:
    itr: 1
    load_from: "/Users/ak4598/Desktop/kaggle-pipeline/output/Amex/Amex_0.779224_20220817090821/Amex_0.779224_20220817090821.sav"
    train: false
    save: true

  clf:
    init:
      # basic
      boosting_type: "dart"
      num_leaves: 31
      max_depth: -1
      learning_rate: 0.1
      n_estimators: 100
      subsample_for_bin: 200000
      objective: "binary"
      class_weight: balanced
      min_split_gain: 0.0
      min_child_weight: 1.0e-3
      min_child_samples: 20
      subsample: 1.0
      subsample_freq: 0
      colsample_bytree: 1.0
      reg_alpha: 0.0
      reg_lambda: 0.0
      random_state: null
      n_jobs: 8
      importance_type: "split"

      # extra
      xgboost_dart_mode: true

    cross_validation: 5
    searching_space:
      num_leaves:
        search: true
        space:
          low: 10
          high: 10000
          q: 1

      max_depth:
        search: true
        space:
          low: 2
          high: 80
          q: 1

      learning_rate:
        search: true
        space:
          low: 0.002
          high: 0.09

      n_estimators:
        search: true
        space:
          low: 5
          high: 1500
          q: 10

      subsample_for_bin:
        search: true
        space:
          low: 100
          high: 20000
          q: 100

      min_split_gain:
        search: true
        space:
          low: 0.0
          high: 1000.0

      min_child_weight:
        search: true
        space:
          low: 0.0001
          high: 0.5

      reg_alpha:
        search: true
        space:
          low: 0.0
          high: 2.0
          q: 0.01

      reg_lambda:
        search: true
        space:
          low: 0.0
          high: 2.0
          q: 0.01
