modules:
  data: "AmexDataManager"
  model: "XGB_Hyperopt"
  metric: "Amex"

dataset:
  prepare: false
  sampling: "NA"

model:
  train:
    itr: 1
    load_from: ""
    train: true
    save: true

  clf:
    init:
      n_estimators: 100
      max_depth: 1
      objective: "binary:logistic"
      tree_method: hist
      booster: "dart"
      use_label_encoder: false
      learning_rate: 0.002
      n_jobs: 8

    cross_validation: 5
    searching_space:
      n_estimators:
        search: true
        space:
          low: 5
          high: 1500
          q: 1

      max_depth:
        search: true
        space:
          low: 2
          high: 80
          q: 1
